docs: Minor fix to Directory structure
error: The app.js file should contains route definitions, configuration
and/or manual bootstrap (if required). - contains

correct: The app.js file should contain route definitions,
configuration and/or manual bootstrap (if required). - contain